model:
  embedding_dim: 128
  num_heads: 4
  hidden_dim: 256
  num_layers: 2
  num_classes: 4
  max_seq_length: 128

training:
  batch_size: 64
  learning_rate: 0.0002
  weight_decay: 1e-6
  num_epochs: 20